name: Compile and Test Java Api

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh
      - name: Build and Test
        working-directory: .
        run: ./gradlew build test dokkaHtml --info --stacktrace
      - name: Prepare Dokka doc locally
        working-directory: .
        run: ./.github/scripts/prepare_javadoc.sh
      - name: Deploy Dokka doc to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true